// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://vbntpdgxzqkgvueuljag.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibnRwZGd4enFrZ3Z1ZXVsamFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4MTI0NTQsImV4cCI6MjA0NjM4ODQ1NH0.9yJs71UY9DtxOueYsueMo0u1_C_KYT0BP4tfwBM__9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);